[build]
  base = "frontend"        # Netlify runs the build FROM /frontend
  command = "npm ci && npm run build"
  publish = "dist"         # <-- relative to /frontend, so just "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
